### ISSUE TITLE
Details about the attack?

### ISSUE THREAD

**Issue by jedisct1** [ALRBP/Attack-Argon2i#1]
Hi Amaury,

Beyond that source code, are details about the attack available?

Thanks!

**Comment by jedisct1** [comment]
Bump?

**Comment by ALRBP** [comment]
Having no news from my internship supervisor about possible publication of this work, I uploaded my internship report on this repository. Hope this will be usefull.

**Comment by jedisct1** [comment]
Thanks a lot for your research and for sharing.
